# Generated by Django 3.1.6 on 2021-02-05 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategory', models.CharField(max_length=60)),
                ('createDateCategory', models.DateTimeField(auto_now_add=True)),
                ('updateDateCategory', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlePost', models.CharField(max_length=60)),
                ('contentPost', models.CharField(max_length=60)),
                ('imagePost', models.ImageField(upload_to='media/BlogApp/images')),
                ('createDatePost', models.DateTimeField(auto_now_add=True)),
                ('updateDatePost', models.DateTimeField(auto_now_add=True)),
                ('authorPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoryPost', models.ManyToManyField(to='BlogApp.Category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
