# Generated by Django 3.1.6 on 2021-02-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleService', models.CharField(max_length=60)),
                ('contentService', models.CharField(max_length=60)),
                ('imageService', models.ImageField(upload_to='')),
                ('createDateService', models.DateTimeField(auto_now_add=True)),
                ('updateDateService', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
