# Generated by Django 3.1.6 on 2021-02-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicesApp', '0002_auto_20210204_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='imageService',
            field=models.ImageField(upload_to='ServicesApp/media/images'),
        ),
    ]
