# Generated by Django 3.1.6 on 2021-02-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicesApp', '0004_auto_20210204_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='imageService',
            field=models.ImageField(upload_to='ServicesApp/images'),
        ),
    ]
