# Generated by Django 3.1.6 on 2021-02-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicesApp', '0005_auto_20210204_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='imageService',
            field=models.ImageField(upload_to='media/ServicesApp/images'),
        ),
    ]
